### ISSUE TITLE
Not using EKF attitude quaternion

### ISSUE THREAD

**Issue by kd0aij** [PyFlightCoach/FlightData#2]
The dataflash log contains NKQ1 and/or XKQ1 records containing the quaternion representing the body-to-world
transform. These are what I'm using in Octave for vehicle attitude since there are no problems with singularities as with the Euler roll/pitch/yaw angles in the ATT record.
I'm pretty sure the "1" in the record name represents the "primary" EKF core (AP can run EKF2 and EKF3 concurrently on each of multiple IMUs if the hardware is present). At any given time, the core selected as primary will be the one with the best health estimate. 

*** update:
I forgot to mention that in recent logs the EKF quaternions are contained in NKQ and XKQ messages and the core number is contained in the new field "C".

**Comment by kd0aij** [comment]
The quaternion elements are called Q1-4 in the NKQ and XKQ records, but these correspond to w,x,y,z.
This is a plot of the W term for cores 0 and 1 from a tailsitter VTOL simulation in which I appear to have upset one (or perhaps both) of the EKF cores. They disagree quite a bit beginning around 15:29:06 although it appears that later on, they differ only in the sign of W which is OK as long as the direction of xyz is flipped too.  Anyway, you have to look at the value of the C field to determine which core the values are coming from, and the MAVProxy graphing tool takes the desired core in the form of a subscript to the record name: XKQ[C].
If you ever get a log with attitudes that are obviously wrong, looking at the individual EKF cores would be useful.

![image](https://user-images.githubusercontent.com/2300221/120871389-b9353d00-c558-11eb-8140-921a6f4e4c60.png)

**Comment by ThomasDavid0** [comment]
Thanks, it looks like it should be a simple change, and would simplify the process quite a bit. Are the xkq or nkq fields always populated regardless of the parameters set?

**Comment by kd0aij** [comment]
Since the EKF is required, there should always be one or both of those records in every log (and the recommended FlightCoach parameters include AHRS_EKF_TYPE=3 for EKF3).  The DCM is used as an emergency fallback to re-init the EKF if/when it diverges.

**Comment by ThomasDavid0** [comment]
I've added this in commit 62f102d
